services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ort
      MONGO_INITDB_ROOT_PASSWORD: ort
      MONGO_INITDB_DATABASE: ort
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
